project:
  type: book
  output-dir: docs

book:
  title: "Praxis-IT"
  downloads: ["pdf"]
  repo-url: "https://github.com/bsenst/praxis-it"
  issue-url: "https://github.com/bsenst/praxis-it/issues"
  repo-actions: ["edit", "issue"]
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - einleitung.qmd
    - praxisverwaltung.qmd
    - anamneseerhebung.qmd
    - medizinisches-wissen.qmd
    - part: "Kommunikation"
      chapters:
      - telefonanlage.qmd
      - telefonassistenz.qmd
      - kimdienst.qmd
      - kurznachrichtendienst.qmd
      - terminbuchung.qmd
      - videosprechstunde.qmd
      - telemedizin.qmd
      - wartezimmer.qmd
    - part: "Fachdisziplinen"
      chapters:
      - gefaessmedizin.qmd
      - wunddokumentation.qmd
      - rheumatologie.qmd
      - ambulantes-operieren.qmd
      - zahnarzt.qmd
    - part: "Verwaltung"
      chapters:
      - buchhaltung.qmd
      - qualitaetsmanagement.qmd
      - dienstplanung.qmd
      - datenschutz.qmd
      - gesetzgebung.qmd
    - diskurs.qmd
    - zusammenfassung.qmd
    - referenzen.qmd

bibliography: referenzen.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



