project:
  type: book
  output-dir: docs

book:
  title: "Praxis-IT"
  downloads: ["pdf"]
  repo-url: "https://github.com/bsenst/praxis-it"
  issue-url: "https://github.com/bsenst/praxis-it/issues"
  repo-actions: ["edit", "issue"]
  chapters:
    - index.qmd
    - einleitung.qmd
    - praxisverwaltung.qmd
    - qualitaetsmanagement.qmd
    - telefonassistenz.qmd
    - anamneseerhebung.qmd
    - kimdienst.qmd
    - dienstplanung.qmd
    - zusammenfassung.qmd
    - referenzen.qmd

bibliography: referenzen.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



