project:
  type: book
  output-dir: docs

book:
  title: "Praxis-IT"
  downloads: ["pdf", "epub", "docx"]
  repo-actions: ["edit", "source", "issue"]
  chapters:
    - index.qmd
    - einleitung.qmd
    - praxisverwaltung.qmd
    - qualitaetsmanagement.qmd
    - telefonassistenz.qmd
    - zusammenfassung.qmd
    - referenzen.qmd

bibliography: referenzen.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



